In [1]:
import numpy as np

In [2]:
r = np.array( [ [ 0, 1, 0, 0, 0, 0, 0 ], [ 0, 1/6, 5/6, 0, 0, 0, 0 ], [ 0, 0, 1/3, 2/3, 0, 0, 0 ], [ 0, 0, 0, 1/2, 1/2, 0, 0],
               [ 0, 0, 0, 0, 2/3, 1/3, 0 ], [ 0, 0, 0, 0, 0, 5/6, 1/6 ], [ 0, 0, 0, 0, 0, 0, 1 ] ] )

In [3]:
r

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.16666667, 0.83333333, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.33333333, 0.66666667, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.5       , 0.5       ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.66666667,
        0.33333333, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.83333333, 0.16666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        ]])

In [11]:
np.linalg.inv( np.identity( 6 ) - r[ :6, :6 ] ) @ np.ones( ( 6, 1 ) )  

array([[14.7],
       [13.7],
       [12.5],
       [11. ],
       [ 9. ],
       [ 6. ]])

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.16666667, 0.83333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.33333333, 0.66666667, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.5       , 0.5       ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.66666667,
        0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.83333333]])