In [1]:
import numpy as np


In [5]:
def states( d, v ):
    return 64 * ( d - 1 ) + v[ 0 ] * 1 + v[ 1 ] * 2 + v[ 2 ] * 4 + v[ 3 ] * 8 + v[ 4 ] * 16 + v[ 5 ] * 32

In [23]:
A = np.zeros( ( 385, 385 ) )
for d in range( 1, 7 ):
    for a0 in range( 2 ):
        for a1 in range( 2 ):
            for a2 in range( 2 ):
                for a3 in range( 2 ):
                    for a4 in range( 2 ):
                        for a5 in range( 2 ):
                            v = np.asarray( [ a0, a1, a2, a3, a4, a5 ] )
                            state_ = states( d, v )
                            for i in range( 1, 7 ):
                                m = np.asarray( [ a0, a1, a2, a3, a4, a5 ] )
                                m[ abs( d - i ) ] = 1
                                if all( m == np.ones( 6 ) ):
                                    A[ state_, -1 ] = 1 
                                else:
                                    state_x = states( i, m )
                                    A[ state_, state_x ] += 1 / 6

In [24]:
a = np.linalg.inv( np.identity( 384 ) - A[ : -1, : -1 ] )
a

array([[1.        , 0.2       , 0.02943725, ..., 0.02969992, 0.11285414,
        0.        ],
       [0.        , 1.2       , 0.        , ..., 0.03684808, 0.        ,
        0.        ],
       [0.        , 0.        , 1.02943725, ..., 0.        , 0.12000231,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.63243996, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.71428571,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [25]:
sum( a[ 0 ] )

23.771221030410675

In [28]:
g = a @ (np.ones( ( 384, 1 ) ) )
g

array([[23.77122103],
       [23.15340986],
       [23.6046914 ],
       [22.94099777],
       [23.40544701],
       [22.70415788],
       [23.2073859 ],
       [22.44260316],
       [23.15710372],
       [22.42957978],
       [22.9486679 ],
       [22.15328054],
       [22.6711057 ],
       [21.7951787 ],
       [22.38467742],
       [21.375     ],
       [21.8987647 ],
       [21.05781184],
       [21.60879954],
       [20.65547282],
       [21.4109663 ],
       [20.42857143],
       [21.04300868],
       [19.88235294],
       [21.0815076 ],
       [20.04961898],
       [20.69266181],
       [19.47058824],
       [20.41329923],
       [19.11764706],
       [19.8       ],
       [18.        ],
       [14.3609922 ],
       [13.15124522],
       [14.02613496],
       [12.68823529],
       [13.65022106],
       [12.21247576],
       [13.22736573],
       [11.58823529],
       [13.17760939],
       [11.66167968],
       [12.73076923],
       [11.        ],
       [12.18129923],
       [10

In [30]:
( g[ 0 ] + g[ 64 ] + g[ 64 * 2 ] + g[ 64 * 3 ] + g[ 64 * 4 ] + g[ 64 * 5 ] ) / 6

array([24.84844129])

In [31]:
g[ 64 * 5 ]

array([23.77122103])

In [32]:
g[ 64 * 4 ]

array([25.27138286])

In [33]:
g[ 64 * 3 ]

array([25.50271996])

In [34]:
g[ 64 * 2 ]

array([25.50271996])

In [35]:
g[ 64 ]

array([25.27138286])

In [36]:
g[ 0 ]

array([23.77122103])