In [3]:
def state( l ):
    return sum( [ l[ i ] * 2**i for i in range( 6 ) ] )

In [4]:
state( [ 1,0,1,0,1,0 ] )

21

In [5]:
import numpy as np
import math

In [6]:
A = np.zeros( ( 64, 64 ) )
for a1 in range( 2 ):
    for a2 in range( 2 ):
        for a3 in range( 2 ):
            for a4 in range( 2 ):
                for a5 in range( 2 ):
                    for a6 in range( 2 ):
                      
                        l = np.asarray( [ a1, a2, a3, a4, a5, a6 ] )
                        if all( l == np.ones( 6 ) ):
                            continue
                        s = state( l )
                      
                        for i in range( 6 ):
                            w = np.asarray( [ a1, a2, a3, a4, a5, a6 ] )
                            if l[ i ] == 0:
                                w[ i ] += 1
                                ss = state( w )
                                
                            else:
                                m = np.zeros( 6, dtype = int )
                                m[ i ] = 1
                                ss = state( m )
                                
                            A[ s, ss ] = 1 / 6
                                

In [7]:
A[3]

array([0.        , 0.16666667, 0.16666667, 0.        , 0.        ,
       0.        , 0.        , 0.16666667, 0.        , 0.        ,
       0.        , 0.16666667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [8]:
state( [ 0, 0, 0, 0, 0, 1 ] )

32

In [9]:
np.linalg.inv( np.identity(63) - A[ : -1, : -1 ] ) @ np.ones( ( 63, 1 ) )

array([[179.8],
       [178.8],
       [178.8],
       [177.6],
       [178.8],
       [177.6],
       [177.6],
       [175.5],
       [178.8],
       [177.6],
       [177.6],
       [175.5],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [178.8],
       [177.6],
       [177.6],
       [175.5],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [175.5],
       [170.2],
       [170.2],
       [150. ],
       [178.8],
       [177.6],
       [177.6],
       [175.5],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [175.5],
       [170.2],
       [170.2],
       [150. ],
       [177.6],
       [175.5],
       [175.5],
       [170.2],
       [175.5],
       [170.2],
       [170.2],
       [150. ],
       [175.5],
       [170.2],
       [170.2],
       [150. ],
       [170.2],
       [150. ],
       [

In [10]:
w = l

In [11]:
w[0]+=1
w

array([1., 0., 0., 0., 0., 0.])

In [28]:
state( [ 1, 1, 1, 1, 1, 1] )

63

In [39]:
1-(5/6)**6

0.6651020233196159

In [43]:
1-((5/6)**12+math.comb(12,1)*(1/6)*(5/6)**11)

0.6186673737323085

In [44]:
1-((5/6)**18+math.comb(18,1)*(1/6)*(5/6)**17+math.comb(18,2)*(1/6)**2*(5/6)**16)

0.5973456859477229