In [2]:
import numpy as op


In [4]:
def rolls_to_state( v ):
    return 1 + v[ 0 ] + v[ 1 ] * 3 + v[ 2 ] * 9 + v[ 3 ] * 27 + v[ 4 ] * 81 + v[ 5 ] * 243 

In [24]:
rolls_to_state( [ 2, 0, 0, 0, 0, 0 ] )

3

In [41]:
A = op.zeros( ( 730, 730 ) )
for a1 in range( 3 ):
    for a2 in range( 3 ):
        for a3 in range( 3 ):
            for a4 in range( 3 ):
                for a5 in range( 3 ):
                    for a6 in range( 3 ):
                        v = op.array( [ a1, a2, a3, a4, a5, a6 ] )
                        s = rolls_to_state( v )
                        c = 0
                        for _ in v:
                            if _ == 2:
                                c += 1
                        A[ s, 0 ] = c / 6
                        if s == 3:
                            print( c )
                        for i in range( len( v ) ):
                            w = op.array( [ a1, a2, a3, a4, a5, a6 ] )
                            if w[ i ] < 2:
                                w[ i ] += 1
                                ss = rolls_to_state( w )
                                A[ s, ss ] = 1 / 6


1


In [43]:
A

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.83333333, 0.        , 0.        , ..., 0.        , 0.16666667,
        0.        ],
       [0.83333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.16666667],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [42]:
A[ 3 ]

array([0.16666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.16666667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16666667, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [44]:
op.linalg.inv( op.identity( 729 ) - A[1:,1:] ) @ op.ones( ( 729, 1 ) )

array([[7.29554434],
       [6.29554434],
       [4.09976209],
       [6.29554434],
       [5.53470079],
       [3.71971451],
       [4.09976209],
       [3.71971451],
       [2.66482339],
       [6.29554434],
       [5.53470079],
       [3.71971451],
       [5.53470079],
       [4.94219393],
       [3.41336591],
       [3.71971451],
       [3.41336591],
       [2.49723508],
       [4.09976209],
       [3.71971451],
       [2.66482339],
       [3.71971451],
       [3.41336591],
       [2.49723508],
       [2.66482339],
       [2.49723508],
       [1.91628086],
       [6.29554434],
       [5.53470079],
       [3.71971451],
       [5.53470079],
       [4.94219393],
       [3.41336591],
       [3.71971451],
       [3.41336591],
       [2.49723508],
       [5.53470079],
       [4.94219393],
       [3.41336591],
       [4.94219393],
       [4.47102195],
       [3.16190844],
       [3.41336591],
       [3.16190844],
       [2.35570988],
       [3.71971451],
       [3.41336591],
       [2.497