In [1]:
import numpy as np

In [23]:
# A[ 0, 1 ] = 1
# A[ 1, 2 ] = 1/6
# A[ 1, 3 ] = 5/6
# A[ 2, 0 ] = 1/3
# A[ 2, 2 ] = 1/6
# A[ 2, 4 ] = 5/6
# A[ 3, 4 ] = 1/3
# A[ 3, 6 ] = 2/3
# A[ 4, 4 ] = 1/6
# A[ 4, 5 ] = 1/6
# A[ 4, 7 ] = 2/3
# A[ 5, 5 ] = 1/3
# A[ 5, 8 ] = 2/3


In [5]:
A[3]

array([0.        , 0.        , 0.        , 0.        , 0.33333333,
       0.        , 0.66666667, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [7]:
def index_to_state_translator( i ):
    if i == 0:
        return [ 0, 0 ]
    elif i == 1:
        return [ 1, 0 ]
    elif i == 2:
        return [ 1, 1 ]
    elif i == 3:
        return [ 2, 0 ]
    elif i == 4:
        return [ 2, 1 ]
    elif i == 5:
        return [ 2, 2 ]
    elif i == 6:
        return [ 3, 0 ]
    elif i == 7:
        return [ 3, 1 ]
    elif i == 8:
        return [ 3, 2 ]
    elif i == 9:
        return [ 3, 3 ]
    elif i == 10:
        return [ 4, 0 ]
    elif i == 11:
        return [ 4, 1 ]
    elif i == 12:
        return [ 4, 2 ]
    elif i == 13:
        return [ 4, 3 ]
    elif i == 14:
        return [ 4, 4 ]
    elif i == 15:
        return [ 5, 0 ]
    elif i == 16:
        return [ 5, 1 ]
    elif i == 17:
        return [ 5, 2 ]
    elif i == 18:
        return [ 5, 3 ]
    elif i == 19:
        return [ 5, 4 ]
    elif i == 20:
        return [ 5, 5 ]
    elif i == 21:
        return [ 6, 0 ]
    elif i == 22:
        return [ 6, 1 ]
    elif i == 23:
        return [ 6, 2 ]
    elif i == 24:
        return [ 6, 3 ]
    elif i == 25:
        return [ 6, 4 ]
    elif i == 26:
        return [ 6, 5 ]
    elif i == 27:
        return [ 6, 6 ]

In [31]:
A = np.zeros( ( 28, 28 ) )
for i in range(27):
    [ a, b ] = index_to_state_translator( i )    
    if a == b:
        if a == 6:
            A[ i, i ] = 1
        else:
            A[ i, i ] = a / 6
            A[ i, i + a + 1 ] = 1 - a / 6
    elif a > b:
        if b == 0:
            if a == 6:
                A[ i, i + 1 ] = 1
            else:    
                A[ i, i + 1 ] = a / 6  
                A[ i, i + a + 1 ] = 1 - a / 6 # e.g. state(2,0) to (3,0), index going up 2+1, the length of states start with a
        else:
            if a == 6:
                A[ i, i ] = b / 6
                A[ i, i + 1 ] = ( a - b ) / 6
            else:
                A[ i, i ] = b / 6  
                A[ i, i + 1 ] = ( a - b ) / 6
                A[ i, i + a + 1 ] = ( 6 - a ) / 6
            


In [32]:
A[2] == A[ 1 ]

array([ True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
np.linalg.inv( np.identity( 27 ) - A[ :27, :27 ] ) @ np.ones( ( 27, 1 ) )

array([[24.1338692 ],
       [23.1338692 ],
       [22.84963278],
       [21.99071648],
       [21.64963278],
       [21.28298611],
       [20.66125833],
       [20.24129444],
       [19.78298611],
       [19.27777778],
       [19.08122222],
       [18.54683333],
       [17.95138889],
       [17.27777778],
       [16.5       ],
       [17.15      ],
       [16.44      ],
       [15.625     ],
       [14.66666667],
       [13.5       ],
       [12.        ],
       [14.7       ],
       [13.7       ],
       [12.5       ],
       [11.        ],
       [ 9.        ],
       [ 6.        ]])